### ISSUE TITLE
[FEATURE REQUEST] Add abilities to manual update ElevenClock&Langurage pack version

### ISSUE THREAD

**Issue by terrencewei** [marticliment/ElevenClock#1107]
Hi, this software is awesome and I love it!
I've noticed that there were options in the settings page to update ElevenClock and language pack automatically and silently in the background, but I'm wondering if there will be an option to let me update the software and language when I'm needed manually such as adding some buttons in the right-click clock menu or clock settings page like "Check for updates" or "Check for language pack updates", because my habit is doesn't like the automatic updates and I wants to "update them only when I wants to" and unfortunately I can't find an option to let me manual  update them, the only way to update expect enable auto-update is to going to Github release page and download the installer then install the update.(And the Microsoft Store still keeps the out-of-dated version(v.3.9.6) today since v4.0.0 has been released 3 weeks ago!)
Thanks!

**Comment by marticliment** [comment]
The fact that version 3.9.6 is not getting updates is due to an external issue with freenom nameservers.

You can get ElevenClock to ask for updates by disabling "Automatically install updates":
![image](https://user-images.githubusercontent.com/53119851/216958606-c622b6e5-aa1d-45b6-b232-c714c6e83052.png)

Regarding language updates, they are just simple josn files downloaded on launch and stored in a temporary folder. They are not updates for the executable itself.
