### ISSUE TITLE
Your 11Clock program is infinitely unreliable!

### ISSUE THREAD

**Issue by Draskic** [marticliment/ElevenClock#1198]
It is enough to change the date manually for some reason (it doesn't matter what for now!) and it no longer appears in Windows 11 (OS Build 22631.1835) in any case.
It can be seen that it is not in the standard locations on the disk (C:\Program Files (x86) and C:\Program Files) and this shows that it is not a standard approach!
Please do not ask for additional questions because we did not deserve to refine the program for you, but simply refine it!
Hello and thank you!
Drasko Divic, Croatia

**Comment by marticliment** [comment]
Hello,

> It can be seen that it is not in the standard locations on the disk (C:\Program Files (x86) and C:\Program Files) and this shows that it is not a standard approach

ElevenClock is installed under %localappdata%\Programs\ElevenClock, the _standard_ directory for user-scoped programs (the ones that are not installed machine-wide).
Before pointing with your finger at me and telling me that I did develop a non-standard program, I would like you to please do a 3-second google search, because you will find that this decision actually stands for a reason, that is compatibility with users who don't have administrator rights (let's say, for example, a school or enterprise-managed windows 11 device)



> Please do not ask for additional questions because we did not deserve to refine the program for you, but simply refine it!

You are not paying anything for this app, and I get no revenue from it. I develop it because I want to, nobody forces me to do so.
I have done my best to fix the issues you posted here, but sometimes issues are caused by external factors that can't be modified by _fixing_ ElevenClock, therefore I can't help with. It should also be noted that from the ~30k active users nobody but you has complained about those issues. 

Moreover, I will ask questions if I don't understand what you post. My english is not perfect and sometimes I can't understand what you post, or I just simply need more information about the environment you are running ElevenClock on. I don't know if you have ever developed an app, but it is quite time-consuming and hard, and trust me, lots of effort have gone into ElevenClock, both from me and from the contributors, to get the best app possible. If the application crashes at some point because of some specific parameter that no one but twenty people in the whole world have set, I'm sorry but I will need more details to understand what is happening. 

This is **not** the first message you send _demanding_ for a feature or a fix. If you don't like ElevenClock, uninstall it and install T-Clock or any other clock utility you want. You are free to do so, and trust me, I don't care if you do so, since I don't get any type of income or revenue based on the amount of users that run ElevenClock. Therefore, I ask you to start being respectful.

#### If you post any other comment that does continue this demanding attitude, or that does contain disrespectful content, you will be banned from this repository. <br> If you start being respectful, I will be pleased to try to fix (without getting paid and using my free time) the issue you are having, in order to make ElevenClock a better app for everyone.
#### The decision is yours. If you want me to attempt to fix this issue please open a new support ticket, with a proper, respectful title and message.

Thank you,

Martí Climent.
