### ISSUE TITLE
[ENHANCEMENT] (Enter your description here) Allow a way to have fractional seconds besides microseconds

### ISSUE THREAD

**Issue by 1000goalgaming** [marticliment/ElevenClock#1302]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

It would be cool if we could decide how much precision we want instead of the default 6 digits provided by `%f`. 

### Describe how this improvement could help users.

Allow for centi/milliseconds to be shown instead of microseconds

**Comment by marticliment** [comment]
> Allow for centi/milliseconds to be shown instead of microseconds

In the best scenario, your monitor would allow you only to see 1/60 of the time (assuing you are on 60Hz), and due to ElevenClock limitations that would be more of 1/3~1/4 of a second. Furthermore, due to these same limitations, that decimal number won't be accurate with the current system time (it would have an offset of an extra 1/4 of a second).  On 120Hz+ monitors ElevenClock limitations still exist, and therefore having decimal time won't work.
